name: Ontology Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [1.2.20]
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}
      
      - name: Install dependencies
        run: bun install
      
      - name: Run linter
        run: bun run lint
      
      - name: Build project
        run: bun run build
      
      - name: Run tests with coverage
        run: bun test --coverage
      
      - name: Check ontology consistency
        run: |
          bun run dist/cli/index.js analyze --path .
          bun run dist/cli/index.js stats
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: coverage/

  build-extension:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.20
      
      - name: Install root dependencies
        run: bun install
      
      - name: Build server
        run: bun run build
      
      - name: Install extension dependencies
        working-directory: ./vscode-client
        run: bun install
      
      - name: Build extension
        working-directory: ./vscode-client
        run: bun run compile
      
      - name: Package extension
        working-directory: ./vscode-client
        run: bunx vsce package
      
      - name: Upload extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: vscode-extension
          path: vscode-client/*.vsix

  release:
    runs-on: ubuntu-latest
    needs: [test, build-extension]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.20
      
      - name: Install dependencies
        run: bun install
      
      - name: Build for release
        run: bun run build
      
      - name: Download extension artifact
        uses: actions/download-artifact@v3
        with:
          name: vscode-extension
          path: ./artifacts
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false
      
      - name: Upload Extension to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/ontology-lsp-1.0.0.vsix
          asset_name: ontology-lsp-${{ github.run_number }}.vsix
          asset_content_type: application/octet-stream